# Generated by Django 4.2.6 on 2023-10-10 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_citizen_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_citizens', to='citizens.province', verbose_name='Provincia'),
        ),
    ]
